/**
 * Regression: a setting changed in-game must survive the guest's own exit AND a page
 * reload, and be applied on the next boot.
 *
 * The whole loop runs through Quake II's own UI (Options → "always run" → Quit → Y),
 * because that is where it broke: the overlay commits OPFS writes behind a debounce,
 * every exit path raised the durability barrier fire-and-forget, and a commit that lost
 * its writable lock was swallowed. The loss is per written RANGE, so config.cfg came
 * back with a NUL hole — and Quake's `exec config.cfg` does Cbuf_AddText over a buffer
 * whose first byte is 0, so strlen is 0 and NOTHING is applied. Saved, yet gone.
 *
 * fsRead alone CANNOT test this: it serves the overlay's in-memory copy and always looks
 * complete. Only a read after a real teardown proves durability.
 *
 *   WGB=G:/WGB/running/quake2.wgb bun tools/harness.ts run tools/examples/quake2-settings-persist.harness.ts
 */
import { harness } from "../harness";

const WGB = process.env.WGB ?? "/apps/external-wgb/quake2.wgb";
const VK = { ESC: 0x1b, DOWN: 0x28, LEFT: 0x25, RIGHT: 0x27, RETURN: 0x0d, Y: 0x59 };
const CFG = "C:\\baseq2\\config.cfg";

const press = async (...keys: number[]) => {
  const c = harness();
  for (const k of keys) c.keyHold(k, 120).sleep(450);
  await c.sleep(700).run();
};
const readConfig = async (): Promise<string> => {
  const r = await harness().call("fsRead", CFG, { maxBytes: 65536, encoding: "utf8" }).run();
  return String((r as any).steps[0].result?.content ?? "");
};

await harness().openWgb(WGB).sleep(26000).run();

// Flip AWAY from whatever is on disk, so a run that persists nothing cannot pass.
const before = (await readConfig()).match(/set cl_run "([^"]*)"/)?.[1] ?? "0";
const expected = before === "1" ? "0" : "1";
const toggle = before === "1" ? VK.LEFT : VK.RIGHT;

// Options → "always run" → toggle. Menu cursor starts at the first item in both menus.
await press(VK.ESC);
await press(VK.DOWN, VK.DOWN, VK.RETURN);
await press(VK.DOWN, VK.DOWN, VK.DOWN, VK.DOWN, VK.DOWN, toggle);
await press(VK.ESC);

// Main menu → Quit → confirm. The guest writes config.cfg on the way out.
await press(VK.DOWN, VK.DOWN, VK.RETURN);
await press(VK.Y);

// Teardown, then look at what actually reached OPFS.
await harness().openWgb(WGB).sleep(20000).run();
const cfg = await readConfig();

const leadingNul = cfg.length - cfg.replace(/^\0+/, "").length;
const clRun = (cfg.match(/set cl_run "([^"]*)"/) ?? [])[1];
console.log(JSON.stringify({ bytes: cfg.length, leadingNul, before, expected, clRun, bindings: /generated by quake/.test(cfg) }, null, 1));

if (leadingNul > 0) throw new Error(`config.cfg has a ${leadingNul}-byte NUL hole — a commit was lost`);
if (!/generated by quake/.test(cfg)) throw new Error("config.cfg lost the bindings pass (fopen \"w\")");
if (clRun !== expected) throw new Error(`setting did not persist: cl_run=${clRun ?? "(absent)"} — expected "${expected}"`);
console.log("OK — settings survived the guest exit and a reload");
