#!/usr/bin/env tsx

/**
 * Generate Index Tool
 *
 * CLI tool to generate auto-index files for atomic modules
 * Scans module directories and creates index.ts files that aggregate implementations
 */

import * as fs from 'fs';
import * as path from 'path';
import { capitalizeApiName as capitalize, getSafeImportName } from '../src/worker/api/naming';

function generateMonolithicIndex(moduleName: string, importPath: string = `../${moduleName}`): string {
    const className = capitalize(moduleName);
    const lines: string[] = [];

    lines.push(`// Auto-generated index for ${moduleName} module`);
    lines.push("");
    lines.push(`export { ${className}, ${className} as ${moduleName}Module } from '${importPath}';`);

    return lines.join("\n");
}

function collectAtomicFiles(dir: string, moduleDir: string): Array<{ category: string; relativePath: string }> {
    const result: Array<{ category: string; relativePath: string }> = [];

    // The emitted order is the order the export tables are merged in, so it must not depend
    // on the host: readdir is sorted on NTFS and arbitrary on APFS/ext4. This is NTFS's order.
    const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((x, y) => {
        const a = x.name.toUpperCase();
        const b = y.name.toUpperCase();
        return a < b ? -1 : a > b ? 1 : 0;
    });
    for (const entry of entries) {
        if (entry.name === 'index.ts') {
            continue;
        }

        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            result.push(...collectAtomicFiles(fullPath, moduleDir));
            continue;
        }

        if (entry.isFile() && entry.name.endsWith('.ts')) {
            const category = path.basename(entry.name, '.ts');
            const relativePath = path.relative(moduleDir, fullPath);
            result.push({ category, relativePath });
        }
    }

    return result;
}

function getExportFactoryName(fileContent: string): string | null {
    const functionMatch = fileContent.match(/export function (create[A-Za-z0-9_]+Exports)\b/);
    if (functionMatch) {
        return functionMatch[1];
    }
    const constMatch = fileContent.match(/export const (create[A-Za-z0-9_]+Exports)\b/);
    if (constMatch) {
        return constMatch[1];
    }
    return null;
}

function hasThunkExports(fileContent: string): boolean {
    // Checks if the file actually exports a symbol named 'exports' (thunk map)
    return /export\s+const\s+exports\s*[=:]/.test(fileContent) ||
           /export\s*\{[^}]*\bexports\b/.test(fileContent);
}

function getFastPathRegisterName(fileContent: string): string | null {
    const functionMatch = fileContent.match(/export function (registerFastPath[A-Za-z0-9_]+Functions)\b/);
    if (functionMatch) {
        return functionMatch[1];
    }
    const constMatch = fileContent.match(/export const (registerFastPath[A-Za-z0-9_]+Functions)\b/);
    if (constMatch) {
        return constMatch[1];
    }
    return null;
}

function isMonolithicModuleClass(fileContent: string): string | null {
    // Check if file exports a class implementing IModule (monolithic module)
    const classMatch = fileContent.match(/export class (\w+) implements IModule/);
    return classMatch ? classMatch[1] : null;
}

function isAutoGeneratedIndex(content: string): boolean {
    return content.includes("Auto-generated index for");
}

function generateModuleIndexFromDirectory(moduleName: string, modulePath: string): string {
    const moduleDir = path.dirname(modulePath); // Get directory containing the module
    let atomicFiles: Array<{ category: string; relativePath: string }> = [];
    let hasDirectory = false;
    try {
        const entries = fs.readdirSync(moduleDir);
        hasDirectory = true;
    } catch (error) {
        hasDirectory = false;
    }

    if (hasDirectory) {
        atomicFiles = collectAtomicFiles(moduleDir, moduleDir);
    }

    // First check if there's a monolithic module class file in the directory (e.g., dinput/dinput.ts)
    const monolithicInDir = path.join(moduleDir, `${moduleName}.ts`);
    if (fs.existsSync(monolithicInDir)) {
        try {
            const content = fs.readFileSync(monolithicInDir, 'utf-8');
            const className = isMonolithicModuleClass(content);
            if (className) {
                // This is a monolithic module inside the directory - use local import
                return generateMonolithicIndex(moduleName, `./${moduleName}`);
            }
        } catch (e) {}
    }

    if (atomicFiles.length === 0) {
        // Check if there's a monolithic file in parent directory
        const monolithicPath = path.join(path.dirname(moduleDir), `${moduleName}.ts`);

        if (fs.existsSync(monolithicPath)) {
            return generateMonolithicIndex(moduleName, `../${moduleName}`);
        }
        return `// No atomic files found in ${moduleDir}\n`;
    }

    const lines: string[] = [];

    lines.push(`// Auto-generated index for ${moduleName} module`);
    lines.push(`// This file aggregates all atomic implementations`);
    lines.push(`// Generated from directory scan: ${path.relative(process.cwd(), moduleDir).split(path.sep).join('/')}`);
    lines.push("");
    lines.push(`import { IModule } from '../../core/module';`);
    lines.push(`import { Process } from '../../core/process';`);
    lines.push(`import { ThunkImplementation } from '../../core/thunking/thunk-dispatcher';`);
    lines.push("");

    // Import all atomic files
    const filesWithExports: Array<{ category: string; relativePath: string; importName: string; fastPathName?: string }> = [];
    for (const fileInfo of atomicFiles) {
        const { category, relativePath } = fileInfo;
        const importName = getSafeImportName(category);
        const relativeImportPath = `./${relativePath.replace(/\.ts$/, '').replace(/\\/g, '/')}`;

        // Special handling for kernel32 which uses direct exports
        if (moduleName === 'kernel32') {
            const fullPath = path.join(moduleDir, relativePath);
            try {
                const fileContent = fs.readFileSync(fullPath, 'utf-8');
                if (!hasThunkExports(fileContent)) continue; // utility file, not a thunk module
            } catch (error) {
                console.warn(`Warning: Could not read ${fullPath}, skipping`);
                continue;
            }
            lines.push(`import { exports as ${importName} } from '${relativeImportPath}';`);
            filesWithExports.push({ category, relativePath, importName });
        } else {
            // Check if file exports a create*Exports factory and import that name.
            const fullPath = path.join(moduleDir, relativePath);
            try {
                const fileContent = fs.readFileSync(fullPath, 'utf-8');
                const exportName = getExportFactoryName(fileContent);
                const fastPathName = getFastPathRegisterName(fileContent);
                
                if (exportName || fastPathName) {
                    const imports = [];
                    if (exportName) imports.push(`${exportName} as ${importName}`);
                    if (fastPathName) imports.push(`${fastPathName} as registerFastPath${importName}`);
                    
                    lines.push(`import { ${imports.join(', ')} } from '${relativeImportPath}';`);
                    filesWithExports.push({ 
                        category, 
                        relativePath, 
                        importName, 
                        fastPathName: fastPathName ? `registerFastPath${importName}` : undefined 
                    });
                }
            } catch (error) {
                // Skip files that can't be read
                console.warn(`Warning: Could not read ${fullPath}, skipping`);
            }
        }
    }

    lines.push("");

    // Generate module class
    lines.push(`export class ${capitalize(moduleName)} implements IModule {`);
    lines.push(`    name = '${moduleName}';`);
    lines.push(`    exports: Record<string, ThunkImplementation> = {};`);
    lines.push("");

    lines.push(`    initialize(process: Process): void {`);

    // Aggregate exports from all atomic files that have exports
    for (const fileInfo of filesWithExports) {
        const { category, importName, fastPathName } = fileInfo;
        lines.push(`        // ${category} functions`);

        // Special handling for kernel32 which uses direct exports
        if (moduleName === 'kernel32') {
            lines.push(`        Object.assign(this.exports, ${importName});`);
        } else {
            if (importName) {
                // Not all files have thunk exports (some might only have fast paths)
                const fullPath = path.join(moduleDir, fileInfo.relativePath);
                const fileContent = fs.readFileSync(fullPath, 'utf-8');
                if (getExportFactoryName(fileContent)) {
                    lines.push(`        Object.assign(this.exports, ${importName}());`);
                }
            }
        }

        if (fastPathName) {
            lines.push(`        ${fastPathName}(process.dispatcher);`);
        }
    }

    lines.push(`    }`);

    // Check if any file exports a reset function for this module
    const resetFunctionName = `reset${capitalize(moduleName)}SharedState`;
    let resetImportFile: string | null = null;
    
    for (const fileInfo of atomicFiles) {
        const fullPath = path.join(moduleDir, fileInfo.relativePath);
        try {
            const fileContent = fs.readFileSync(fullPath, 'utf-8');
            if (fileContent.includes(`export function ${resetFunctionName}`)) {
                resetImportFile = `./${fileInfo.relativePath.replace(/\.ts$/, '').replace(/\\/g, '/')}`;
                break;
            }
        } catch (e) {}
    }

    if (resetImportFile) {
        // We need to add the import at the top, but we already pushed lines.
        // Let's insert it before the class definition.
        const importLine = `import { ${resetFunctionName} } from '${resetImportFile}';`;
        const classDefIndex = lines.findIndex(l => l.startsWith('export class'));
        lines.splice(classDefIndex - 1, 0, importLine);

        lines.push("");
        lines.push(`    reset(): void {`);
        lines.push(`        ${resetFunctionName}();`);
        lines.push(`    }`);
    }

    lines.push(`}`);

    return lines.join("\n");
}

function generateModuleIndex(moduleName: string, modulePath: string): void {
    console.log(`Generating index for ${moduleName}...`);

    const indexContent = generateModuleIndexFromDirectory(moduleName, modulePath);
    const indexPath = path.join(path.dirname(modulePath), 'index.ts');

    if (fs.existsSync(indexPath)) {
        const existing = fs.readFileSync(indexPath, 'utf-8');
        if (!isAutoGeneratedIndex(existing)) {
            console.warn(`Skipping ${indexPath} (custom index detected)`);
            return;
        }
    }

    fs.writeFileSync(indexPath, indexContent, 'utf-8');
    console.log(`Generated ${indexPath}`);
}

function generateAllModuleIndexes(): void {
    const modulesDir = path.join(process.cwd(), 'src', 'worker', 'modules');
    const modules = ['kernel32', 'user32', 'd3d9', 'dsound', 'advapi32', 'winmm', 'gdi32', 'ole32', 'ddraw', 'dinput', 'dplayx', 'mss32', 'comctl32', 'glide2x', 'opengl32'];

    console.log('Generating indexes for all modules...');

    for (const moduleName of modules) {
        // First try directory-based module
        const moduleIndexPath = path.join(modulesDir, moduleName, 'index.ts');
        if (fs.existsSync(moduleIndexPath)) {
            generateModuleIndex(moduleName, moduleIndexPath);
            continue;
        }

        // Try monolithic module
        const monolithicPath = path.join(modulesDir, `${moduleName}.ts`);
        if (fs.existsSync(monolithicPath)) {
            const indexContent = generateMonolithicIndex(moduleName);
            const indexPath = path.join(modulesDir, moduleName, 'index.ts');

            // Ensure directory exists
            const moduleDir = path.dirname(indexPath);
            if (!fs.existsSync(moduleDir)) {
                fs.mkdirSync(moduleDir, { recursive: true });
            }

            if (fs.existsSync(indexPath)) {
                const existing = fs.readFileSync(indexPath, 'utf-8');
                if (!isAutoGeneratedIndex(existing)) {
                    console.warn(`Skipping ${indexPath} (custom index detected)`);
                    continue;
                }
            }

            fs.writeFileSync(indexPath, indexContent, 'utf-8');
            console.log(`Generated ${indexPath}`);
            continue;
        }

        console.warn(`Module ${moduleName} not found (neither directory nor monolithic file)`);
    }

    console.log('All indexes generated successfully!');
}

function main(): void {
    const args = process.argv.slice(2);

    if (args.length === 0) {
        // Generate all indexes
        generateAllModuleIndexes();
    } else if (args.length === 1) {
        // Generate index for specific module
        const moduleName = args[0];
        const modulePath = path.join(process.cwd(), 'src', 'worker', 'modules', moduleName, 'index.ts');

        if (!fs.existsSync(modulePath)) {
            console.error(`Module ${moduleName} not found at ${modulePath}`);
            process.exit(1);
        }

        generateModuleIndex(moduleName, modulePath);
    } else {
        console.error('Usage: tsx generate-index.ts [module-name]');
        console.error('  module-name: kernel32, user32, d3d9, dsound (optional - generates all if not specified)');
        process.exit(1);
    }
}

main();
