#!/usr/bin/env bun
/**
 * Build-time: generate reference argCount map from tools/reference/win32 sig.json files.
 * Used by api-registry to resolve argCount when a function is not in our API (e.g. PE import from non-thunked DLL).
 * Ensures we never emit stdcall stubs with wrong RET N.
 */

import * as fs from "fs";
import * as path from "path";

const REFERENCE_DIR = path.join(process.cwd(), "tools/reference/win32");
const OUT_PATH = path.join(process.cwd(), "src/worker/reference-argcounts.generated.ts");

function normalizeName(name: string): string {
    return name.replace(/^[_@]+/, "").replace(/@\d+$/, "").toLowerCase();
}

type RefMap = Record<string, Record<string, number>>;

function collect(): RefMap {
    const out: RefMap = {};
    if (!fs.existsSync(REFERENCE_DIR)) return out;
    const dirs = fs.readdirSync(REFERENCE_DIR, { withFileTypes: true }).filter((d) => d.isDirectory());
    for (const dir of dirs) {
        const subPath = path.join(REFERENCE_DIR, dir.name);
        const files = fs.readdirSync(subPath).filter((f) => f.endsWith(".sig.json"));
        for (const file of files) {
            const fullPath = path.join(subPath, file);
            const data = JSON.parse(fs.readFileSync(fullPath, "utf-8"));
            const moduleName = (data.module || dir.name).toLowerCase().replace(/\.dll$/, "");
            if (!Array.isArray(data.functions)) continue;
            if (!out[moduleName]) out[moduleName] = {};
            for (const f of data.functions) {
                if (typeof f.argCount !== "number") continue;
                const norm = normalizeName(f.name);
                out[moduleName][norm] = f.argCount;
            }
        }
    }
    return out;
}

/**
 * Emit order must not depend on readdir order, or every contributor's filesystem
 * reshuffles the generated file and the diff drowns the real change.
 */
function sortMap(map: RefMap): RefMap {
    const out: RefMap = {};
    for (const mod of Object.keys(map).sort()) {
        const fns: Record<string, number> = {};
        for (const fn of Object.keys(map[mod]).sort()) fns[fn] = map[mod][fn];
        out[mod] = fns;
    }
    return out;
}

function emit(map: RefMap): string {
    const lines: string[] = [
        "// Auto-generated by tools/generate-reference-argcounts.ts – do not edit",
        "// Used by api-registry to resolve argCount for PE imports not in our API.",
        "",
        "export type ReferenceArgCountMap = Record<string, Record<string, number>>;",
        "",
        "export const REFERENCE_ARG_COUNTS: ReferenceArgCountMap = " + JSON.stringify(map, null, 2) + ";",
        "",
    ];
    return lines.join("\n");
}

function main(): void {
    const map = sortMap(collect());
    fs.writeFileSync(OUT_PATH, emit(map), "utf-8");
    const total = Object.values(map).reduce((s, m) => s + Object.keys(m).length, 0);
    console.log(`[generate-reference-argcounts] Wrote ${OUT_PATH} (${Object.keys(map).length} modules, ${total} functions)`);
}

main();
