#!/usr/bin/env bun
/**
 * Generate the two facts the loader needs to serve api-set contracts and kernelbase.dll:
 *
 *   src/worker/core/apiset-schema.generated.ts   contract -> host DLL (the ApiSetSchema)
 *   src/worker/api/kernelbase-exports.generated.ts   the names kernelbase.dll exports
 *
 * Source: Wine's dlls/apisetschema/apisetschema.spec and dlls/kernelbase/kernelbase.spec
 * (export tables and the schema are interface facts; no code is taken). A `#@ stub` line
 * is a Windows export Wine leaves out, so it counts as exported.
 *
 * Usage: bun tools/generate-apiset-exports.ts [--wine g:/sources/wine]
 */

import * as fs from "fs";
import * as path from "path";

const argv = process.argv.slice(2);
const wineIdx = argv.indexOf("--wine");
const WINE = wineIdx >= 0 ? argv[wineIdx + 1] : "g:/sources/wine";

const schemaSpec = fs.readFileSync(path.join(WINE, "dlls/apisetschema/apisetschema.spec"), "utf8");
const kernelbaseSpec = fs.readFileSync(path.join(WINE, "dlls/kernelbase/kernelbase.spec"), "utf8");

/** Windows resolves a contract by its name up to the last hyphen: the patch number is ignored. */
function contractKey(name: string): string {
    return name.toLowerCase().replace(/-\d+$/, "");
}

const schema: Array<[string, string]> = [];
for (const line of schemaSpec.split(/\r?\n/)) {
    const m = line.match(/^apiset\s+(\S+)\s*=\s*(\S*)/);
    if (!m) continue;
    const host = m[2].toLowerCase().replace(/\.dll$/, "");
    if (!host) continue; // a contract with no host resolves to nothing
    schema.push([contractKey(m[1]), host]);
}
schema.sort((a, b) => a[0].localeCompare(b[0]));

const names = new Set<string>();
for (const line of kernelbaseSpec.split(/\r?\n/)) {
    const m = line.match(/^#?\s*@\s+\S+\s+((?:-\S+\s+)*)([A-Za-z_][A-Za-z0-9_]*)/);
    if (!m) continue;
    const arch = m[1].match(/-arch=(\S+)/)?.[1];
    if (arch && (arch.startsWith("!") ? arch.slice(1).split(",").includes("i386") : !arch.split(",").includes("i386"))) {
        continue; // not exported on x86
    }
    names.add(m[2]);
}
const sortedNames = [...names].sort();

const header = (what: string) =>
    `// Auto-generated by tools/generate-apiset-exports.ts from Wine's ${what} — do not edit.\n\n`;

fs.writeFileSync(path.join(process.cwd(), "src/worker/core/apiset-schema.generated.ts"),
    header("apisetschema.spec") +
    "/** Api-set contract (name up to its last hyphen, lower case) -> host DLL base name. */\n" +
    "export const APISET_SCHEMA: Readonly<Record<string, string>> = {\n" +
    schema.map(([k, v]) => `    "${k}": "${v}",`).join("\n") + "\n};\n");

fs.writeFileSync(path.join(process.cwd(), "src/worker/api/kernelbase-exports.generated.ts"),
    header("kernelbase.spec") +
    "/** Every name kernelbase.dll exports on x86. */\n" +
    "export const KERNELBASE_EXPORT_NAMES: readonly string[] = [\n" +
    sortedNames.map(n => `    "${n}",`).join("\n") + "\n];\n");

console.log(`apiset contracts: ${schema.length}, kernelbase exports: ${sortedNames.length}`);
