/**
 * The flat d3dx9 effect pass-state table: a compiled effect encodes each state assignment as an
 * `operation` integer, and that integer is a direct INDEX into this table, not an enum value.
 * Ids are therefore dense 0x00..0xB2 with no gaps — any reordering or omission silently
 * remaps every effect in the wild. Transcribed from Wine's d3dx9_36 state_table[] and
 * cross-checked against vkd3d's fx_2_pass_states[].
 *
 * `op` is resolved to its numeric value; what it MEANS depends on `cls` — a D3D enum for the
 * render/texture-stage/sampler/transform classes, an index into the sub-enums below for
 * Material, Light and ShaderConst, and meaningless (0) for the classes whose id is the whole
 * identity (Fvf, NPatchMode, Texture, SetSampler, VertexShader, PixelShader, LightEnable).
 */

/** Wine's STATE_CLASS, in its order so the numbering cross-reads. */
export const enum EffectStateClass {
    LightEnable = 0,
    Fvf = 1,
    Light = 2,
    Material = 3,
    NPatchMode = 4,
    PixelShader = 5,
    RenderState = 6,
    SetSampler = 7,
    SamplerState = 8,
    Texture = 9,
    TextureStage = 10,
    Transform = 11,
    VertexShader = 12,
    ShaderConst = 13,
    Unknown = 14,
}

/** `op` for EffectStateClass.Material. */
export const enum EffectMaterialMember {
    Diffuse = 0,
    Ambient = 1,
    Specular = 2,
    Emissive = 3,
    Power = 4,
}

/** `op` for EffectStateClass.Light. */
export const enum EffectLightMember {
    Type = 0,
    Diffuse = 1,
    Specular = 2,
    Ambient = 3,
    Position = 4,
    Direction = 5,
    Range = 6,
    Falloff = 7,
    Attenuation0 = 8,
    Attenuation1 = 9,
    Attenuation2 = 10,
    Theta = 11,
    Phi = 12,
}

/** `op` for EffectStateClass.ShaderConst. */
export const enum EffectShaderConstType {
    VSFloat = 0,
    VSBool = 1,
    VSInt = 2,
    PSFloat = 3,
    PSBool = 4,
    PSInt = 5,
}

export interface EffectStateInfo {
    readonly cls: EffectStateClass;
    readonly op: number;
    readonly name: string;
}

export const EFFECT_STATE_TABLE: readonly EffectStateInfo[] = [
    { cls: EffectStateClass.RenderState, op: 7, name: "D3DRS_ZENABLE" },
    { cls: EffectStateClass.RenderState, op: 8, name: "D3DRS_FILLMODE" },
    { cls: EffectStateClass.RenderState, op: 9, name: "D3DRS_SHADEMODE" },
    { cls: EffectStateClass.RenderState, op: 14, name: "D3DRS_ZWRITEENABLE" },
    { cls: EffectStateClass.RenderState, op: 15, name: "D3DRS_ALPHATESTENABLE" },
    { cls: EffectStateClass.RenderState, op: 16, name: "D3DRS_LASTPIXEL" },
    { cls: EffectStateClass.RenderState, op: 19, name: "D3DRS_SRCBLEND" },
    { cls: EffectStateClass.RenderState, op: 20, name: "D3DRS_DESTBLEND" },
    { cls: EffectStateClass.RenderState, op: 22, name: "D3DRS_CULLMODE" },
    { cls: EffectStateClass.RenderState, op: 23, name: "D3DRS_ZFUNC" },
    { cls: EffectStateClass.RenderState, op: 24, name: "D3DRS_ALPHAREF" },
    { cls: EffectStateClass.RenderState, op: 25, name: "D3DRS_ALPHAFUNC" },
    { cls: EffectStateClass.RenderState, op: 26, name: "D3DRS_DITHERENABLE" },
    { cls: EffectStateClass.RenderState, op: 27, name: "D3DRS_ALPHABLENDENABLE" },
    { cls: EffectStateClass.RenderState, op: 28, name: "D3DRS_FOGENABLE" },
    { cls: EffectStateClass.RenderState, op: 29, name: "D3DRS_SPECULARENABLE" },
    { cls: EffectStateClass.RenderState, op: 34, name: "D3DRS_FOGCOLOR" },
    { cls: EffectStateClass.RenderState, op: 35, name: "D3DRS_FOGTABLEMODE" },
    { cls: EffectStateClass.RenderState, op: 36, name: "D3DRS_FOGSTART" },
    { cls: EffectStateClass.RenderState, op: 37, name: "D3DRS_FOGEND" },
    { cls: EffectStateClass.RenderState, op: 38, name: "D3DRS_FOGDENSITY" },
    { cls: EffectStateClass.RenderState, op: 48, name: "D3DRS_RANGEFOGENABLE" },
    { cls: EffectStateClass.RenderState, op: 52, name: "D3DRS_STENCILENABLE" },
    { cls: EffectStateClass.RenderState, op: 53, name: "D3DRS_STENCILFAIL" },
    { cls: EffectStateClass.RenderState, op: 54, name: "D3DRS_STENCILZFAIL" },
    { cls: EffectStateClass.RenderState, op: 55, name: "D3DRS_STENCILPASS" },
    { cls: EffectStateClass.RenderState, op: 56, name: "D3DRS_STENCILFUNC" },
    { cls: EffectStateClass.RenderState, op: 57, name: "D3DRS_STENCILREF" },
    { cls: EffectStateClass.RenderState, op: 58, name: "D3DRS_STENCILMASK" },
    { cls: EffectStateClass.RenderState, op: 59, name: "D3DRS_STENCILWRITEMASK" },
    { cls: EffectStateClass.RenderState, op: 60, name: "D3DRS_TEXTUREFACTOR" },
    { cls: EffectStateClass.RenderState, op: 128, name: "D3DRS_WRAP0" },
    { cls: EffectStateClass.RenderState, op: 129, name: "D3DRS_WRAP1" },
    { cls: EffectStateClass.RenderState, op: 130, name: "D3DRS_WRAP2" },
    { cls: EffectStateClass.RenderState, op: 131, name: "D3DRS_WRAP3" },
    { cls: EffectStateClass.RenderState, op: 132, name: "D3DRS_WRAP4" },
    { cls: EffectStateClass.RenderState, op: 133, name: "D3DRS_WRAP5" },
    { cls: EffectStateClass.RenderState, op: 134, name: "D3DRS_WRAP6" },
    { cls: EffectStateClass.RenderState, op: 135, name: "D3DRS_WRAP7" },
    { cls: EffectStateClass.RenderState, op: 198, name: "D3DRS_WRAP8" },
    { cls: EffectStateClass.RenderState, op: 199, name: "D3DRS_WRAP9" },
    { cls: EffectStateClass.RenderState, op: 200, name: "D3DRS_WRAP10" },
    { cls: EffectStateClass.RenderState, op: 201, name: "D3DRS_WRAP11" },
    { cls: EffectStateClass.RenderState, op: 202, name: "D3DRS_WRAP12" },
    { cls: EffectStateClass.RenderState, op: 203, name: "D3DRS_WRAP13" },
    { cls: EffectStateClass.RenderState, op: 204, name: "D3DRS_WRAP14" },
    { cls: EffectStateClass.RenderState, op: 205, name: "D3DRS_WRAP15" },
    { cls: EffectStateClass.RenderState, op: 136, name: "D3DRS_CLIPPING" },
    { cls: EffectStateClass.RenderState, op: 137, name: "D3DRS_LIGHTING" },
    { cls: EffectStateClass.RenderState, op: 139, name: "D3DRS_AMBIENT" },
    { cls: EffectStateClass.RenderState, op: 140, name: "D3DRS_FOGVERTEXMODE" },
    { cls: EffectStateClass.RenderState, op: 141, name: "D3DRS_COLORVERTEX" },
    { cls: EffectStateClass.RenderState, op: 142, name: "D3DRS_LOCALVIEWER" },
    { cls: EffectStateClass.RenderState, op: 143, name: "D3DRS_NORMALIZENORMALS" },
    { cls: EffectStateClass.RenderState, op: 145, name: "D3DRS_DIFFUSEMATERIALSOURCE" },
    { cls: EffectStateClass.RenderState, op: 146, name: "D3DRS_SPECULARMATERIALSOURCE" },
    { cls: EffectStateClass.RenderState, op: 147, name: "D3DRS_AMBIENTMATERIALSOURCE" },
    { cls: EffectStateClass.RenderState, op: 148, name: "D3DRS_EMISSIVEMATERIALSOURCE" },
    { cls: EffectStateClass.RenderState, op: 151, name: "D3DRS_VERTEXBLEND" },
    { cls: EffectStateClass.RenderState, op: 152, name: "D3DRS_CLIPPLANEENABLE" },
    { cls: EffectStateClass.RenderState, op: 154, name: "D3DRS_POINTSIZE" },
    { cls: EffectStateClass.RenderState, op: 155, name: "D3DRS_POINTSIZE_MIN" },
    { cls: EffectStateClass.RenderState, op: 166, name: "D3DRS_POINTSIZE_MAX" },
    { cls: EffectStateClass.RenderState, op: 156, name: "D3DRS_POINTSPRITEENABLE" },
    { cls: EffectStateClass.RenderState, op: 157, name: "D3DRS_POINTSCALEENABLE" },
    { cls: EffectStateClass.RenderState, op: 158, name: "D3DRS_POINTSCALE_A" },
    { cls: EffectStateClass.RenderState, op: 159, name: "D3DRS_POINTSCALE_B" },
    { cls: EffectStateClass.RenderState, op: 160, name: "D3DRS_POINTSCALE_C" },
    { cls: EffectStateClass.RenderState, op: 161, name: "D3DRS_MULTISAMPLEANTIALIAS" },
    { cls: EffectStateClass.RenderState, op: 162, name: "D3DRS_MULTISAMPLEMASK" },
    { cls: EffectStateClass.RenderState, op: 163, name: "D3DRS_PATCHEDGESTYLE" },
    { cls: EffectStateClass.RenderState, op: 165, name: "D3DRS_DEBUGMONITORTOKEN" },
    { cls: EffectStateClass.RenderState, op: 167, name: "D3DRS_INDEXEDVERTEXBLENDENABLE" },
    { cls: EffectStateClass.RenderState, op: 168, name: "D3DRS_COLORWRITEENABLE" },
    { cls: EffectStateClass.RenderState, op: 170, name: "D3DRS_TWEENFACTOR" },
    { cls: EffectStateClass.RenderState, op: 171, name: "D3DRS_BLENDOP" },
    { cls: EffectStateClass.RenderState, op: 172, name: "D3DRS_POSITIONDEGREE" },
    { cls: EffectStateClass.RenderState, op: 173, name: "D3DRS_NORMALDEGREE" },
    { cls: EffectStateClass.RenderState, op: 174, name: "D3DRS_SCISSORTESTENABLE" },
    { cls: EffectStateClass.RenderState, op: 175, name: "D3DRS_SLOPESCALEDEPTHBIAS" },
    { cls: EffectStateClass.RenderState, op: 176, name: "D3DRS_ANTIALIASEDLINEENABLE" },
    { cls: EffectStateClass.RenderState, op: 178, name: "D3DRS_MINTESSELLATIONLEVEL" },
    { cls: EffectStateClass.RenderState, op: 179, name: "D3DRS_MAXTESSELLATIONLEVEL" },
    { cls: EffectStateClass.RenderState, op: 180, name: "D3DRS_ADAPTIVETESS_X" },
    { cls: EffectStateClass.RenderState, op: 181, name: "D3DRS_ADAPTIVETESS_Y" },
    { cls: EffectStateClass.RenderState, op: 182, name: "D3DRS_ADAPTIVETESS_Z" },
    { cls: EffectStateClass.RenderState, op: 183, name: "D3DRS_ADAPTIVETESS_W" },
    { cls: EffectStateClass.RenderState, op: 184, name: "D3DRS_ENABLEADAPTIVETESSELLATION" },
    { cls: EffectStateClass.RenderState, op: 185, name: "D3DRS_TWOSIDEDSTENCILMODE" },
    { cls: EffectStateClass.RenderState, op: 186, name: "D3DRS_CCW_STENCILFAIL" },
    { cls: EffectStateClass.RenderState, op: 187, name: "D3DRS_CCW_STENCILZFAIL" },
    { cls: EffectStateClass.RenderState, op: 188, name: "D3DRS_CCW_STENCILPASS" },
    { cls: EffectStateClass.RenderState, op: 189, name: "D3DRS_CCW_STENCILFUNC" },
    { cls: EffectStateClass.RenderState, op: 190, name: "D3DRS_COLORWRITEENABLE1" },
    { cls: EffectStateClass.RenderState, op: 191, name: "D3DRS_COLORWRITEENABLE2" },
    { cls: EffectStateClass.RenderState, op: 192, name: "D3DRS_COLORWRITEENABLE3" },
    { cls: EffectStateClass.RenderState, op: 193, name: "D3DRS_BLENDFACTOR" },
    { cls: EffectStateClass.RenderState, op: 194, name: "D3DRS_SRGBWRITEENABLE" },
    { cls: EffectStateClass.RenderState, op: 195, name: "D3DRS_DEPTHBIAS" },
    { cls: EffectStateClass.RenderState, op: 206, name: "D3DRS_SEPARATEALPHABLENDENABLE" },
    { cls: EffectStateClass.RenderState, op: 207, name: "D3DRS_SRCBLENDALPHA" },
    { cls: EffectStateClass.RenderState, op: 208, name: "D3DRS_DESTBLENDALPHA" },
    { cls: EffectStateClass.RenderState, op: 209, name: "D3DRS_BLENDOPALPHA" },
    { cls: EffectStateClass.TextureStage, op: 1, name: "D3DTSS_COLOROP" },
    { cls: EffectStateClass.TextureStage, op: 26, name: "D3DTSS_COLORARG0" },
    { cls: EffectStateClass.TextureStage, op: 2, name: "D3DTSS_COLORARG1" },
    { cls: EffectStateClass.TextureStage, op: 3, name: "D3DTSS_COLORARG2" },
    { cls: EffectStateClass.TextureStage, op: 4, name: "D3DTSS_ALPHAOP" },
    { cls: EffectStateClass.TextureStage, op: 27, name: "D3DTSS_ALPHAARG0" },
    { cls: EffectStateClass.TextureStage, op: 5, name: "D3DTSS_ALPHAARG1" },
    { cls: EffectStateClass.TextureStage, op: 6, name: "D3DTSS_ALPHAARG2" },
    { cls: EffectStateClass.TextureStage, op: 28, name: "D3DTSS_RESULTARG" },
    { cls: EffectStateClass.TextureStage, op: 7, name: "D3DTSS_BUMPENVMAT00" },
    { cls: EffectStateClass.TextureStage, op: 8, name: "D3DTSS_BUMPENVMAT01" },
    { cls: EffectStateClass.TextureStage, op: 9, name: "D3DTSS_BUMPENVMAT10" },
    { cls: EffectStateClass.TextureStage, op: 10, name: "D3DTSS_BUMPENVMAT11" },
    { cls: EffectStateClass.TextureStage, op: 11, name: "D3DTSS_TEXCOORDINDEX" },
    { cls: EffectStateClass.TextureStage, op: 22, name: "D3DTSS_BUMPENVLSCALE" },
    { cls: EffectStateClass.TextureStage, op: 23, name: "D3DTSS_BUMPENVLOFFSET" },
    { cls: EffectStateClass.TextureStage, op: 24, name: "D3DTSS_TEXTURETRANSFORMFLAGS" },
    { cls: EffectStateClass.TextureStage, op: 32, name: "D3DTSS_CONSTANT" },
    { cls: EffectStateClass.NPatchMode, op: 0, name: "NPatchMode" },
    { cls: EffectStateClass.Fvf, op: 0, name: "FVF" },
    { cls: EffectStateClass.Transform, op: 3, name: "D3DTS_PROJECTION" },
    { cls: EffectStateClass.Transform, op: 2, name: "D3DTS_VIEW" },
    { cls: EffectStateClass.Transform, op: 256, name: "D3DTS_WORLD" },
    { cls: EffectStateClass.Transform, op: 16, name: "D3DTS_TEXTURE0" },
    { cls: EffectStateClass.Material, op: 0, name: "MaterialDiffuse" },
    { cls: EffectStateClass.Material, op: 1, name: "MaterialAmbient" },
    { cls: EffectStateClass.Material, op: 2, name: "MaterialSpecular" },
    { cls: EffectStateClass.Material, op: 3, name: "MaterialEmissive" },
    { cls: EffectStateClass.Material, op: 4, name: "MaterialPower" },
    { cls: EffectStateClass.Light, op: 0, name: "LightType" },
    { cls: EffectStateClass.Light, op: 1, name: "LightDiffuse" },
    { cls: EffectStateClass.Light, op: 2, name: "LightSpecular" },
    { cls: EffectStateClass.Light, op: 3, name: "LightAmbient" },
    { cls: EffectStateClass.Light, op: 4, name: "LightPosition" },
    { cls: EffectStateClass.Light, op: 5, name: "LightDirection" },
    { cls: EffectStateClass.Light, op: 6, name: "LightRange" },
    { cls: EffectStateClass.Light, op: 7, name: "LightFallOff" },
    { cls: EffectStateClass.Light, op: 8, name: "LightAttenuation0" },
    { cls: EffectStateClass.Light, op: 9, name: "LightAttenuation1" },
    { cls: EffectStateClass.Light, op: 10, name: "LightAttenuation2" },
    { cls: EffectStateClass.Light, op: 11, name: "LightTheta" },
    { cls: EffectStateClass.Light, op: 12, name: "LightPhi" },
    { cls: EffectStateClass.LightEnable, op: 0, name: "LightEnable" },
    { cls: EffectStateClass.VertexShader, op: 0, name: "Vertexshader" },
    { cls: EffectStateClass.PixelShader, op: 0, name: "Pixelshader" },
    { cls: EffectStateClass.ShaderConst, op: 0, name: "VertexShaderConstantF" },
    { cls: EffectStateClass.ShaderConst, op: 1, name: "VertexShaderConstantB" },
    { cls: EffectStateClass.ShaderConst, op: 2, name: "VertexShaderConstantI" },
    { cls: EffectStateClass.ShaderConst, op: 0, name: "VertexShaderConstant" },
    { cls: EffectStateClass.ShaderConst, op: 0, name: "VertexShaderConstant1" },
    { cls: EffectStateClass.ShaderConst, op: 0, name: "VertexShaderConstant2" },
    { cls: EffectStateClass.ShaderConst, op: 0, name: "VertexShaderConstant3" },
    { cls: EffectStateClass.ShaderConst, op: 0, name: "VertexShaderConstant4" },
    { cls: EffectStateClass.ShaderConst, op: 3, name: "PixelShaderConstantF" },
    { cls: EffectStateClass.ShaderConst, op: 4, name: "PixelShaderConstantB" },
    { cls: EffectStateClass.ShaderConst, op: 5, name: "PixelShaderConstantI" },
    { cls: EffectStateClass.ShaderConst, op: 3, name: "PixelShaderConstant" },
    { cls: EffectStateClass.ShaderConst, op: 3, name: "PixelShaderConstant1" },
    { cls: EffectStateClass.ShaderConst, op: 3, name: "PixelShaderConstant2" },
    { cls: EffectStateClass.ShaderConst, op: 3, name: "PixelShaderConstant3" },
    { cls: EffectStateClass.ShaderConst, op: 3, name: "PixelShaderConstant4" },
    { cls: EffectStateClass.Texture, op: 0, name: "Texture" },
    { cls: EffectStateClass.SamplerState, op: 1, name: "AddressU" },
    { cls: EffectStateClass.SamplerState, op: 2, name: "AddressV" },
    { cls: EffectStateClass.SamplerState, op: 3, name: "AddressW" },
    { cls: EffectStateClass.SamplerState, op: 4, name: "BorderColor" },
    { cls: EffectStateClass.SamplerState, op: 5, name: "MagFilter" },
    { cls: EffectStateClass.SamplerState, op: 6, name: "MinFilter" },
    { cls: EffectStateClass.SamplerState, op: 7, name: "MipFilter" },
    { cls: EffectStateClass.SamplerState, op: 8, name: "MipMapLodBias" },
    { cls: EffectStateClass.SamplerState, op: 9, name: "MaxMipLevel" },
    { cls: EffectStateClass.SamplerState, op: 10, name: "MaxAnisotropy" },
    { cls: EffectStateClass.SamplerState, op: 11, name: "SRGBTexture" },
    { cls: EffectStateClass.SamplerState, op: 12, name: "ElementIndex" },
    { cls: EffectStateClass.SamplerState, op: 13, name: "DMAPOffset" },
    { cls: EffectStateClass.SetSampler, op: 0, name: "Sampler" },
];

/** null rather than a clamped entry: an out-of-range id is a corrupt effect the caller must refuse. */
export function effectStateInfo(id: number): EffectStateInfo | null {
    if (!Number.isInteger(id) || id < 0 || id >= EFFECT_STATE_TABLE.length) return null;
    return EFFECT_STATE_TABLE[id]!;
}
